name: Test

on:
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Install dependencies
      run: sudo apt update && sudo apt-get install -y git make cmake gcovr

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      run: cd test && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..

    - name: Build
      run: cd test/build && make

    - name: Run tests and calculate code coverage
      run: cd test/build && make kvik_test_coverage

    - name: Upload coverage output
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: test/build/kvik_test_coverage
